In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3], 
             [4,5,6]])

a.shape

(2, 3)

In [4]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [8]:
a = np.array([[[1,2,3], [4,5,6], [3,6,2]], [[1,2,3],[4,5,6],[5,3,3]]])

a

array([[[1, 2, 3],
        [4, 5, 6],
        [3, 6, 2]],

       [[1, 2, 3],
        [4, 5, 6],
        [5, 3, 3]]])

In [14]:
a[0][1][1]

array([[[1, 2, 3],
        [4, 5, 6],
        [3, 6, 2]]])

In [16]:
a[:1]

array([[[1, 2, 3],
        [4, 5, 6],
        [3, 6, 2]]])

In [21]:
b = a[:2]
b[0] = 40


a #original array mutated

array([[[40, 40, 40],
        [40, 40, 40],
        [40, 40, 40]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  3,  3]]])

In [22]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[1,3]

8

## Array Attributes

In [25]:
print(a.ndim)
print(a.shape)

print(len(a.shape))

2
(3, 4)
2


In [27]:
print(a.size)
print(a.dtype)

12
int64


In [32]:
"""
Creating basic arrays automatically

"""
print(np.zeros(3))

print(np.ones(4))

print(np.arange(6))

print(np.arange(1, 10, 3))

[0. 0. 0.]
[1. 1. 1. 1.]
[0 1 2 3 4 5]
[1 4 7]


In [33]:
# spacing linearly between a range
print(np.linspace(0, 10, num=5))

[ 0.   2.5  5.   7.5 10. ]


In [34]:
# in numpy, the default dtype is float64, so

x = np.ones(2, dtype=np.int64)
print(x)

[1 1]


## Adding, Removing, and sorting elements

In [35]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

print(np.sort(arr))


[1 2 3 4 5 6 7 8]


In [37]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(np.concatenate((a, b)))

[1 2 3 4 5 6 7 8]


In [38]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [40]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

## Shape / Size of an Array

In [41]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [42]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [43]:
array_example.ndim

3

In [44]:
array_example.size

24

In [45]:
array_example.shape


(3, 2, 4)

In [47]:
a = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print(np.shape(a))

(2, 3)


In [48]:
"""
We can also reshape an array

"""

a = np.arange(6)
b = a.reshape(3, 2)
print(a)

print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
